import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`h-screen overflow-hidden ${inter.className}`}>
        <div className="flex h-full">
          <div className="w-80 bg-[#45B9F2] text-white px-4">
            <Sidebar />
          </div>
          <main className="w-full m-8 bg-white border rounded-lg shadow-2xl">
            <div className="w-full h-[120px] bg-gray-500 rounded-t-lg">hi</div>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
